# Jekyll Configuration

#url: http://0.0.0.0:3000
media_url:
title: ckelly.net
description: The online home of Chris Kelly - includes journal resume and about pages
author: Chris Kelly

permalink: /:title

highlighter: true
lsi: true
